version: 0.2

phases:
  install:
    commands:
      - curl -OL https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb
      - dpkg -i mysql-apt-config*
      - apt update -y
      - apt-get -y install mysql-server
      - composer install
  pre_build:
    commands:
      - service mariadb start
      - /bin/bash ./tests/mkaws.sh
  build:
    commands:
      - echo Run tests 
      - ./vendor/bin/phpunit --bootstrap ./tests/bootstrap.php ./tests/AllTests.php
  post_build:
    commands:
      - echo Build completed on `date`
#  artifacts:
#  files:
