version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install mysql-server -y
      - composer install
  pre_build:
    commands:
      - service mysql start
      - mkdir ./config
      - /bin/bash ./tests/mkaws.sh
  build:
    commands:
      - echo Run tests 
      - ./vendor/bin/phpunit --bootstrap ./tests/bootstrap.php ./tests/AllTests.php
      - mkdir artifacts
      - ./build/buildrelease.py ./artifacts ./
  post_build:
    commands:
      - mv ./artifacts/*.zip ./artifacts/final.zip
      - echo Build completed
  artifacts:
    files:
      - /artifacts/final.zip
