version: 0.2

phases:
  install:
    commands:
      - curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | /bin/bash
      - apt-get update -y
      - apt-get install mariadb-client mariadb-server -y
      - composer install
  pre_build:
    commands:
      - service mariadb start
      - /bin/bash ./tests/mkaws.sh
  build:
    commands:
      - echo Run tests 
      - ./vendor/bin/phpunit --bootstrap ./tests/bootstrap.php ./tests/AllTests.php
  post_build:
    commands:
      - echo Build completed on `date`
#  artifacts:
#  files:
